# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: pyskull.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import pyskull_pb2


class GreeterBase(abc.ABC):

    @abc.abstractmethod
    async def Hail(self, stream):
        pass

    def __mapping__(self):
        return {
            '/pyskull.Greeter/Hail': grpclib.const.Handler(
                self.Hail,
                grpclib.const.Cardinality.UNARY_UNARY,
                pyskull_pb2.HailRequest,
                pyskull_pb2.HailResponse,
            ),
        }


class GreeterStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Hail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/pyskull.Greeter/Hail',
            pyskull_pb2.HailRequest,
            pyskull_pb2.HailResponse,
        )
