FROM python:3.7-alpine
RUN apk --update add linux-headers g++ make
RUN pip install grpcio-tools
RUN pip install grpclib

WORKDIR /opt/app
COPY proto .
RUN python3 -m grpc_tools.protoc -I. --python_out=. --python_grpc_out=. ./pyskull.proto