app:
  image: pyskull:latest
  pullPolicy: IfNotPresent
  replicaCount: 1
  ports:
  - name: http
    containerPort: 80
    protocol: TCP
  - name: grpc
    containerPort: 50051
    protocol: TCP
  - name: metrics
    containerPort: 9100
    protocol: TCP
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  livenessProbe: {}
  readinessProbe: {}
  imagePullSecrets:
  - name: kairosinc-jenkins-pull-secret

service:
  enabled: true
  type: ClusterIP
  http_port: 80
  grpc_port: 50051
  metrics_port: 9100
  annotations:
      prometheus.io/port: "9100"
      prometheus.io/scrape: "true"

hpa:
  enabled: true
  metrics:
  - type: Pods
    pods:
      metricName: my_metric
      targetAverageValue: 3000m
  min: 1
  max: 5