{{ if .Values.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: {{ template "pyskull.fullname" . }}
  labels:
    app: {{ template "pyskull.name" . }}
    chart: {{ template "pyskull.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "pyskull.fullname" . }}
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}
{{- with .Values.hpa.metrics}}
  metrics:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}