{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "pyskull"
  labels:
    app: {{ template "pyskull.name" . }}
    chart: {{ template "pyskull.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.readinessProbe }}
  ports:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    app: {{ template "pyskull.name" . }}
    release: {{ .Release.Name }}
{{- end}}