apiVersion: v1
kind: ConfigMap
Metadata:
  name: {{ template "pyskull.fullname" . }}-siege-config
  labels:
    app: {{ template "pyskull.name" . }}
    chart: {{ template "pyskull.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "configs/siege.conf").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "configs/urls.txt").AsConfig . ) | indent 2 }}